version: 2.1
orbs:
  gradle: circleci/gradle@2.1.0
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
            # Export base64 encoded google-services.json
          # into local bash variables
      - run :
          name: Export Google Services Json
          command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV
      - run:
          # Decode the base64 string
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json

      - run:
          name: Export Api keys
          command: echo 'export api_keys="$api_keys_circleci"' >> $BASH_ENV
      - run:              # Decode the base64 string
          name: Decode Google Services Json
          command: echo $api_keys_circleci | base64 -di > app/src/res/values/api_keys.xml
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
workflows:
  version: 2.1
  workflow:
    jobs:
      - build